openapi: 3.0.2
info:
    title: Billease Merchants. Transaction API
    description: |
        Billease Merchants API. Transactions

        ![Diagram](https://billease.github.io/merchants/diagram.png)

    contact:
        name: IT Department
        url: 'https://www.firstdigitalfinance.com'
        email: api-info@firstdigitalfinance.com
    version: 1.0.0
    x-logo:
        url: 'https://billease.github.io/merchants/billease-logo.png'
        altText: Billease
servers:
    -
        url: 'http://{domain}:{port}/bem-merch-api/'
        description: Server URL
        variables:
            domain:
                default: wateway.web.lt
                description: Back end API
            port:
                default: '80'
                description: Production port
paths:
    /ping:
        summary: Information about service
        description: Get information about service
        get:
            tags:
                - ping
            summary: Information about service
            description: Get information about service
            operationId: ping
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ping'
                            examples:
                                ok:
                                    value:
                                        nam: api name
                                        env: prod
                                        ver: 1.0.1
                                        srv: '2018-10-25T13:12:01'
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/message'
                            examples:
                                Unauthorized:
                                    value:
                                        message: Unauthorized
                '500':
                    description: Internal error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                error:
                                    value:
                                        error: internal server error
components:
    schemas:
        message:
            title: Root Type for message
            description: Some message from the server
            required:
                - message
            type: object
            properties:
                message:
                    description: Message field
                    type: string
            example: |-
                {
                    "message": "no Route matched with those values"
                }
        response:
            title: Root Type for response
            description: Success response message
            type: object
            properties:
                id:
                    format: int32
                    description: Record ID
                    type: integer
            example: |-
                {
                    "id": 25
                }
        pages:
            description: Pagination
            required:
                - current
            type: object
            properties:
                count:
                    format: int32
                    description: Total number of pages
                    type: integer
                previous:
                    format: int32
                    description: Previous page number
                    type: integer
                current:
                    format: int32
                    description: Current page
                    type: integer
                next:
                    format: int32
                    description: Next page number
                    type: integer
            example:
                count: 75
                previous: 4
                current: 5
                next: 6
        error:
            title: main error type
            description: Error object
            required:
                - error
            type: object
            properties:
                error:
                    $ref: '#/components/schemas/error_description'
                    description: Error object
            example:
                error:
                    code: some text
                    message: some text
                    data:
                        field_1:
                            - error message 1
                            - error message 2
                        field_2:
                            - error message
        error_description:
            title: error description type
            description: Error description
            type: object
            properties:
                code:
                    description: Error code
                    type: string
                message:
                    description: Main error message
                    type: string
                data:
                    description: Error data
                    type: object
                    additionalProperties:
                        description: Field error messages
                        type: array
                        items:
                            type: string
        ping:
            title: ping type
            description: Information about service
            type: object
            properties:
                nam:
                    description: Name of the service
                    type: string
                env:
                    description: 'Environment: prod;uat;dev'
                    type: string
                ver:
                    description: Service version
                    type: string
                srv:
                    format: date-time
                    description: Server time
                    type: string
            example: |
                {
                  "nam":"api name",
                  "env": "prod",
                  "ver":"1.0.1",
                  "srv":"2018-10-25T13:12:01"
                }
    securitySchemes:
        security:
            type: oauth2
            description: Security Roles
            flows:
                implicit:
                    authorizationUrl: 'https://example.com/oauth/authorize'
                    scopes:
                        'mer:write': Create/Update information about merchant
                        'shop:write': Create/Update information about merchant
tags:
    -
        name: ping
        description: Information about service
